/* Golf Finder SEQ — service worker.
 *
 * Two jobs:
 *  1. Existence of a fetch handler is what makes Android build a real
 *     standalone WebAPK from "Add to Home screen" (instead of a Chrome
 *     bookmark shortcut). This is the whole reason this file exists.
 *  2. Cache the app shell so it opens offline. Live data (weather, sunset,
 *     space-weather, fonts) is always network-first and simply unavailable
 *     offline — the shell still loads and shows its last state.
 *
 * Bump CACHE when index.html changes so clients pick up the new version.
 */
const CACHE = 'golf-finder-v28';
const SHELL = [
  './', './index.html', './course-maps.json',
  // Self-hosted fonts (see index.html head note). Precaching them same-origin is what
  // removes the old fonts.googleapis.com startup-freeze class entirely and makes text
  // render correctly offline. Syne is variable (one file spans weights 400–800).
  './fonts/dmmono-400-latin.woff2', './fonts/dmmono-400-latin-ext.woff2',
  './fonts/dmmono-500-latin.woff2', './fonts/dmmono-500-latin-ext.woff2',
  './fonts/syne-var-latin.woff2', './fonts/syne-var-latin-ext.woff2',
  './fonts/syne-var-greek.woff2',   // night-sky Bayer designations (α, β, γ…)
];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  const sameOrigin = url.origin === self.location.origin;

  // course-maps.json is regenerated by CI — serve network-first so updates land,
  // falling back to cache when offline. (Cache-first would pin a stale manifest
  // until the next CACHE bump.)
  if (sameOrigin && url.pathname.endsWith('course-maps.json')) {
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  // App shell / same-origin: NETWORK-FIRST so a fresh deploy always lands when
  // online (cache-first used to pin a stale index.html until CACHE was bumped,
  // which silently hid new builds from returning users). Falls back to cache,
  // then to the cached index for navigations, so offline still works.
  if (sameOrigin) {
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() =>
          caches.match(req).then((hit) =>
            hit || (req.mode === 'navigate' ? caches.match('./index.html') : Response.error())
          )
        )
    );
    return;
  }

  // Live data APIs (weather, sunset, space-weather): always go to the network,
  // never cache. Caching a forecast — or worse, a 429 error — would serve
  // stale/broken data later. A failed live call just means that datum is
  // unavailable; the app already handles ok:false gracefully.
  const LIVE_HOSTS = ['api.open-meteo.com', 'api.sunrisesunset.io', 'services.swpc.noaa.gov', 'api.wheretheiss.at'];
  if (LIVE_HOSTS.some((h) => url.hostname.endsWith(h))) {
    e.respondWith(fetch(req));
    return;
  }

  // Any other cross-origin static asset: network-first, cache only real successes.
  // (Fonts used to be here; they're self-hosted same-origin now, handled above.)
  e.respondWith(
    fetch(req)
      .then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      })
      .catch(() => caches.match(req))
  );
});
